// Los 50 actores con más películas rodadas.
// Generado por tools/build-actores.py desde
// top_50_actores_numero_peliculas.xlsx — no editar a mano.
// n: nombre · p: nº de películas · f: archivo en actors/
const ACTORES_TOP = [
  { n: "Samuel L. Jackson", p: 152, f: "samuel-l-jackson.jpg" },
  { n: "Michael Caine", p: 130, f: "michael-caine.jpg" },
  { n: "Robert De Niro", p: 120, f: "robert-de-niro.jpg" },
  { n: "Nicolas Cage", p: 115, f: "nicolas-cage.jpg" },
  { n: "Liam Neeson", p: 95, f: "liam-neeson.jpg" },
  { n: "Morgan Freeman", p: 90, f: "morgan-freeman.jpg" },
  { n: "Anthony Hopkins", p: 88, f: "anthony-hopkins.jpg" },
  { n: "Bruce Willis", p: 88, f: "bruce-willis.jpg" },
  { n: "Tom Hanks", p: 80, f: "tom-hanks.jpg" },
  { n: "Jeff Bridges", p: 75, f: "jeff-bridges.jpg" },
  { n: "Clint Eastwood", p: 72, f: "clint-eastwood.jpg" },
  { n: "Nicole Kidman", p: 70, f: "nicole-kidman.jpg" },
  { n: "Robert Downey Jr.", p: 70, f: "robert-downey-jr.jpg" },
  { n: "Scarlett Johansson", p: 65, f: "scarlett-johansson.jpg" },
  { n: "Johnny Depp", p: 65, f: "johnny-depp.jpg" },
  { n: "Keanu Reeves", p: 65, f: "keanu-reeves.jpg" },
  { n: "Meryl Streep", p: 65, f: "meryl-streep.jpg" },
  { n: "Brad Pitt", p: 61, f: "brad-pitt.jpg" },
  { n: "Denzel Washington", p: 60, f: "denzel-washington.jpg" },
  { n: "Jack Nicholson", p: 60, f: "jack-nicholson.jpg" },
  { n: "Gary Oldman", p: 60, f: "gary-oldman.jpg" },
  { n: "Woody Harrelson", p: 60, f: "woody-harrelson.jpg" },
  { n: "Michelle Yeoh", p: 60, f: "michelle-yeoh.jpg" },
  { n: "Al Pacino", p: 55, f: "al-pacino.jpg" },
  { n: "Harrison Ford", p: 55, f: "harrison-ford.jpg" },
  { n: "Matt Damon", p: 55, f: "matt-damon.jpg" },
  { n: "Cate Blanchett", p: 55, f: "cate-blanchett.jpg" },
  { n: "Penélope Cruz", p: 55, f: "penelope-cruz.jpg" },
  { n: "Dustin Hoffman", p: 55, f: "dustin-hoffman.jpg" },
  { n: "Sean Penn", p: 55, f: "sean-penn.jpg" },
  { n: "Tom Cruise", p: 50, f: "tom-cruise.jpg" },
  { n: "Javier Bardem", p: 50, f: "javier-bardem.jpg" },
  { n: "Julia Roberts", p: 50, f: "julia-roberts.jpg" },
  { n: "Kate Winslet", p: 45, f: "kate-winslet.jpg" },
  { n: "Sandra Bullock", p: 45, f: "sandra-bullock.jpg" },
  { n: "Charlize Theron", p: 45, f: "charlize-theron.jpg" },
  { n: "Natalie Portman", p: 42, f: "natalie-portman.jpg" },
  { n: "Joaquin Phoenix", p: 40, f: "joaquin-phoenix.jpg" },
  { n: "George Clooney", p: 40, f: "george-clooney.jpg" },
  { n: "Dwayne Johnson", p: 40, f: "dwayne-johnson.jpg" },
  { n: "Angelina Jolie", p: 40, f: "angelina-jolie.jpg" },
  { n: "Viola Davis", p: 40, f: "viola-davis.jpg" },
  { n: "Christian Bale", p: 38, f: "christian-bale.jpg" },
  { n: "Cillian Murphy", p: 38, f: "cillian-murphy.jpg" },
  { n: "Will Smith", p: 35, f: "will-smith.jpg" },
  { n: "Leonardo DiCaprio", p: 35, f: "leonardo-dicaprio.jpg" },
  { n: "Ryan Gosling", p: 35, f: "ryan-gosling.jpg" },
  { n: "Emma Stone", p: 30, f: "emma-stone.jpg" },
  { n: "Margot Robbie", p: 30, f: "margot-robbie.jpg" },
  { n: "Timothée Chalamet", p: 20, f: "timothee-chalamet.jpg" },
];
