// directors por puesto de película y foto por persona
// Generado por tools/fetch-people.py --role directors
// Nombres: top_peliculas_taquilla_y_critica.xlsx · Fotos: Wikipedia en inglés
const DIRECTORS = {
  1: ["James Cameron"],
  2: ["Anthony Russo", "Joe Russo"],
  3: ["James Cameron"],
  4: ["James Cameron"],
  5: ["J.J. Abrams"],
  6: ["Anthony Russo", "Joe Russo"],
  7: ["Jon Watts"],
  8: ["Yu Yang"],
  9: ["Jon Watts"],
  10: ["Byron Howard"],
  11: ["Kelsey Mann"],
  12: ["Colin Trevorrow"],
  13: ["Jon Favreau"],
  14: ["Joss Whedon"],
  15: ["James Wan"],
  16: ["James Cameron"],
  17: ["Joseph Kosinski"],
  18: ["Chris Buck", "Jennifer Lee"],
  19: ["Greta Gerwig"],
  20: ["Joss Whedon"],
  21: ["Aaron Horvath", "Michael Jelenic"],
  22: ["Christopher Nolan"],
  23: ["Shawn Levy"],
  24: ["Ryan Coogler"],
  25: ["Rian Johnson"],
  26: ["David Yates"],
  27: ["J.A. Bayona"],
  28: ["Chris Buck", "Jennifer Lee"],
  29: ["Bill Condon"],
  30: ["Brad Bird"],
  31: ["Shane Black"],
  32: ["F. Gary Gray"],
  33: ["Pierre Coffin", "Kyle Balda"],
  34: ["Anthony Russo", "Joe Russo"],
  35: ["James Wan"],
  36: ["Jon Watts"],
  37: ["Anna Boden", "Ryan Fleck"],
  38: ["Peter Jackson"],
  39: ["Michael Bay"],
  40: ["Andrew Stanton"],
  41: ["Sam Mendes"],
  42: ["Michael Bay"],
  43: ["Christopher Nolan"],
  44: ["Todd Phillips"],
  45: ["Josh Cooley"],
  46: ["J.J. Abrams"],
  47: ["Lee Unkrich"],
  48: ["Gore Verbinski"],
  49: ["David Derrick Jr."],
  50: ["Steven Spielberg"],
  51: ["Gareth Edwards"],
  52: ["George Lucas"],
  53: ["Rob Marshall"],
  54: ["Guy Ritchie"],
  55: ["Dean Fleischer Camp"],
  56: ["Pierre Coffin", "Kyle Balda"],
  57: ["Tim Burton"],
  58: ["Andrew Stanton"],
  60: ["Byron Howard", "Rich Moore"],
  61: ["Peter Jackson"],
  63: ["Christopher Nolan"],
  64: ["Colin Trevorrow"],
  65: ["Roger Allers", "Rob Minkoff"],
  66: ["Chris Renaud"],
  67: ["Christopher Nolan"],
  68: ["Pierre Coffin", "Chris Renaud"],
  69: ["Chris Columbus"],
  70: ["Jake Kasdan"],
  71: ["Jared Hess"],
  72: ["Gore Verbinski"],
  73: ["Peter Jackson"],
  74: ["Sam Raimi"],
  75: ["Jon Favreau"],
  76: ["David Yates"],
  77: ["Peter Jackson"],
  78: ["Kyle Balda"],
  79: ["David Yates"],
  80: ["Andrew Stanton"],
  81: ["Andrew Adamson"],
  82: ["Peter Jackson"],
  83: ["David Yates"],
  84: ["George Lucas"],
  85: ["Peter Jackson"],
  86: ["Sam Raimi"],
  87: ["Mike Newell"],
  88: ["Carlos Saldanha"],
  89: ["Chris Renaud"],
  90: ["Steve Martino"],
  91: ["Bryan Singer"],
  92: ["Sam Mendes"],
  93: ["Jon Watts"],
  94: ["Chris Columbus"],
  95: ["Zack Snyder"],
  96: ["Gareth Edwards"],
  97: ["James Gunn"],
  98: ["Francis Lawrence"],
  99: ["Ryan Coogler"],
  100: ["Ruben Fleischer"],
};

const DIRECTOR_PHOTOS = {
  "Aaron Horvath": "aaron-horvath.jpg",
  "Akira Kurosawa": "akira-kurosawa.jpg",
  "Alejandro G. Iñárritu": "alejandro-g-inarritu.jpg",
  "Alfonso Cuarón": "alfonso-cuaron.jpg",
  "Alfred Hitchcock": "alfred-hitchcock.jpg",
  "Andrew Adamson": "andrew-adamson.jpg",
  "Andrew Stanton": "andrew-stanton.jpg",
  "Anna Boden": "anna-boden.jpg",
  "Anthony Russo": "anthony-russo.jpg",
  "Barry Jenkins": "barry-jenkins.jpg",
  "Bill Condon": "bill-condon.jpg",
  "Billy Wilder": "billy-wilder.jpg",
  "Bong Joon-ho": "bong-joon-ho.jpg",
  "Brad Bird": "brad-bird.jpg",
  "Brian De Palma": "brian-de-palma.jpg",
  "Bryan Singer": "bryan-singer.jpg",
  "Byron Howard": "byron-howard.jpg",
  "Carlos Saldanha": "carlos-saldanha.jpg",
  "Charles Chaplin": "charles-chaplin.jpg",
  "Chloé Zhao": "chloe-zhao.jpg",
  "Chris Buck": "chris-buck.jpg",
  "Chris Columbus": "chris-columbus.jpg",
  "Chris Renaud": "chris-renaud.jpg",
  "Christopher Nolan": "christopher-nolan.jpg",
  "Colin Trevorrow": "colin-trevorrow.jpg",
  "Damien Chazelle": "damien-chazelle.jpg",
  "Daniel Kwan": "daniel-kwan.jpg",
  "Daniel Scheinert": "daniel-scheinert.jpg",
  "David Derrick Jr.": "david-derrick-jr.jpg",
  "David Fincher": "david-fincher.jpg",
  "David Lean": "david-lean.jpg",
  "David Yates": "david-yates.jpg",
  "Dean Fleischer Camp": "dean-fleischer-camp.jpg",
  "Ernst Lubitsch": "ernst-lubitsch.jpg",
  "Ethan Coen": "ethan-coen.jpg",
  "F. Gary Gray": "f-gary-gray.jpg",
  "Fernando Meirelles": "fernando-meirelles.jpg",
  "Francis Ford Coppola": "francis-ford-coppola.jpg",
  "Francis Lawrence": "francis-lawrence.jpg",
  "Frank Darabont": "frank-darabont.jpg",
  "Gareth Edwards": "gareth-edwards.jpg",
  "Gene Kelly": "gene-kelly.jpg",
  "George Lucas": "george-lucas.jpg",
  "George Roy Hill": "george-roy-hill.jpg",
  "Giuseppe Tornatore": "giuseppe-tornatore.jpg",
  "Gore Verbinski": "gore-verbinski.jpg",
  "Greta Gerwig": "greta-gerwig.jpg",
  "Guillermo del Toro": "guillermo-del-toro.jpg",
  "Guy Ritchie": "guy-ritchie.jpg",
  "Hayao Miyazaki": "hayao-miyazaki.jpg",
  "Irvin Kershner": "irvin-kershner.jpg",
  "J.A. Bayona": "j-a-bayona.jpg",
  "J.J. Abrams": "j-j-abrams.jpg",
  "Jake Kasdan": "jake-kasdan.jpg",
  "James Cameron": "james-cameron.jpg",
  "James Gunn": "james-gunn.jpg",
  "James Wan": "james-wan.jpg",
  "Jared Hess": "jared-hess.jpg",
  "Jean-Pierre Jeunet": "jean-pierre-jeunet.jpg",
  "Jennifer Lee": "jennifer-lee.jpg",
  "Joe Russo": "joe-russo.jpg",
  "Joel Coen": "joel-coen.jpg",
  "Jon Favreau": "jon-favreau.jpg",
  "Jon Watts": "jon-watts.jpg",
  "Jonathan Demme": "jonathan-demme.jpg",
  "Joseph Kosinski": "joseph-kosinski.jpg",
  "Joseph L. Mankiewicz": "joseph-l-mankiewicz.jpg",
  "Josh Cooley": "josh-cooley.jpg",
  "Joss Whedon": "joss-whedon.jpg",
  "Kelsey Mann": "kelsey-mann.jpg",
  "Kyle Balda": "kyle-balda.jpg",
  "Lee Unkrich": "lee-unkrich.jpg",
  "Luc Besson": "luc-besson.jpg",
  "Martin Scorsese": "martin-scorsese.jpg",
  "Mel Gibson": "mel-gibson.jpg",
  "Michael Bay": "michael-bay.jpg",
  "Michael Curtiz": "michael-curtiz.jpg",
  "Michael Jelenic": "michael-jelenic.jpg",
  "Michel Gondry": "michel-gondry.jpg",
  "Mike Newell": "mike-newell.jpg",
  "Miloš Forman": "milos-forman.jpg",
  "Orson Welles": "orson-welles.jpg",
  "Paul Thomas Anderson": "paul-thomas-anderson.jpg",
  "Peter Jackson": "peter-jackson.jpg",
  "Peter Weir": "peter-weir.jpg",
  "Pierre Coffin": "pierre-coffin.jpg",
  "Quentin Tarantino": "quentin-tarantino.jpg",
  "Rian Johnson": "rian-johnson.jpg",
  "Rich Moore": "rich-moore.jpg",
  "Ridley Scott": "ridley-scott.jpg",
  "Rob Marshall": "rob-marshall.jpg",
  "Rob Minkoff": "rob-minkoff.jpg",
  "Robert Zemeckis": "robert-zemeckis.jpg",
  "Roberto Benigni": "roberto-benigni.jpg",
  "Roger Allers": "roger-allers.jpg",
  "Roman Polanski": "roman-polanski.jpg",
  "Ruben Fleischer": "ruben-fleischer.jpg",
  "Ryan Coogler": "ryan-coogler.jpg",
  "Ryan Fleck": "ryan-fleck.jpg",
  "Sam Mendes": "sam-mendes.jpg",
  "Sam Raimi": "sam-raimi.jpg",
  "Sergio Leone": "sergio-leone.jpg",
  "Shane Black": "shane-black.jpg",
  "Shawn Levy": "shawn-levy.jpg",
  "Sidney Lumet": "sidney-lumet.jpg",
  "Stanley Donen": "stanley-donen.jpg",
  "Stanley Kubrick": "stanley-kubrick.jpg",
  "Steve Martino": "steve-martino.jpg",
  "Steve McQueen": "steve-mcqueen.jpg",
  "Steven Spielberg": "steven-spielberg.jpg",
  "The Wachowskis": "the-wachowskis.jpg",
  "Tim Burton": "tim-burton.jpg",
  "Todd Phillips": "todd-phillips.jpg",
  "Victor Fleming": "victor-fleming.jpg",
  "Wes Anderson": "wes-anderson.jpg",
  "William Wyler": "william-wyler.jpg",
  "Yu Yang": "yu-yang.jpg",
  "Zack Snyder": "zack-snyder.jpg",
};
