// Top 100 películas por recaudación mundial
// Generado por tools/build-data.py · no editar a mano
// Taquilla y año: The Numbers · Director, reparto y Óscars: Filmaffinity
// r = puesto · t = título · g = recaudación · y = año
// o = Óscars ganados · d = director(es) · a = reparto principal
// fa = nota de FilmAffinity · oc = categorías de Óscar ganadas
// Sin o/d/a: la película no está en el Excel ampliado
const MOVIES = [
  { r: 1, t: "Avatar", g: 2923706026, y: 2009, o: 3, fa: 7.2, d: ["James Cameron"], a: ["Sam Worthington", "Zoe Saldana", "Sigourney Weaver", "Stephen Lang", "Michelle Rodriguez"], oc: ["Mejor Fotografía", "Mejores Efectos Visuales", "Mejor Dirección Artística"] },
  { r: 2, t: "Avengers: Endgame", g: 2717503922, y: 2019, o: 0, fa: 7.3, d: ["Anthony Russo", "Joe Russo"], a: ["Robert Downey Jr.", "Chris Evans", "Mark Ruffalo", "Scarlett Johansson", "Chris Hemsworth"] },
  { r: 3, t: "Avatar: The Way of Water", g: 2322902023, y: 2022, o: 1, fa: 6.5, d: ["James Cameron"], a: ["Sam Worthington", "Zoe Saldana", "Sigourney Weaver", "Kate Winslet", "Stephen Lang"], oc: ["Mejores Efectos Visuales"] },
  { r: 4, t: "Titanic", g: 2223048786, y: 1997, o: 11, fa: 6.8, d: ["James Cameron"], a: ["Leonardo DiCaprio", "Kate Winslet", "Billy Zane", "Kathy Bates", "Frances Fisher"], oc: ["Mejor Película", "Mejor Director", "Mejor Montaje", "Mejor Sonido", "Mejor Edición de Sonido", "Mejor Banda Sonora", "Mejor Canción Original", "Mejor Fotografía", "Mejor Dirección Artística", "Mejor Vestuario", "Mejores Efectos Visuales"] },
  { r: 5, t: "Star Wars Ep. VII: The Force Awakens", g: 2056046835, y: 2015, o: 0, d: ["J.J. Abrams"], a: ["Daisy Ridley", "John Boyega", "Adam Driver", "Harrison Ford", "Oscar Isaac"] },
  { r: 6, t: "Avengers: Infinity War", g: 2048158241, y: 2018, o: 0, fa: 7.5, d: ["Anthony Russo", "Joe Russo"], a: ["Robert Downey Jr.", "Chris Hemsworth", "Mark Ruffalo", "Chris Evans", "Scarlett Johansson"] },
  { r: 7, t: "Spider-Man: Brand New Day", g: 2046432089, y: 2026, o: 0, d: ["Jon Watts"], a: ["Tom Holland", "Zendaya", "Jacob Batalon", "Marisa Tomei", "Jon Favreau"] },
  { r: 8, t: "Ne Zha 2", g: 2001155094, y: 2025, o: 0, d: ["Yu Yang"], a: ["Lü Yanting", "Han Mo", "Chen Hao", "Lü Qi", "Liu Tongzi"] },
  { r: 9, t: "Spider-Man: No Way Home", g: 1921206586, y: 2021, o: 0, fa: 6.9, d: ["Jon Watts"], a: ["Tom Holland", "Zendaya", "Benedict Cumberbatch", "Tobey Maguire", "Andrew Garfield"] },
  { r: 10, t: "Zootopia 2", g: 1870309291, y: 2025, o: 0, d: ["Byron Howard"], a: ["Ginnifer Goodwin", "Jason Bateman", "Ke Huy Quan", "Fortune Feimster", "Idris Elba"] },
  { r: 11, t: "Inside Out 2", g: 1698863816, y: 2024, o: 1, d: ["Kelsey Mann"], a: ["Amy Poehler", "Maya Hawke", "Ayo Edebiri", "Lewis Black", "Phyllis Smith"], oc: ["Mejor Película de Animación"] },
  { r: 12, t: "Jurassic World", g: 1671063641, y: 2015, o: 0, fa: 5.8, d: ["Colin Trevorrow"], a: ["Chris Pratt", "Bryce Dallas Howard", "Irrfan Khan", "Vincent D'Onofrio", "Nick Robinson"] },
  { r: 13, t: "The Lion King (2019)", g: 1661454403, y: 2019, o: 0, d: ["Jon Favreau"], a: ["Donald Glover", "Beyoncé", "James Earl Jones", "Seth Rogen", "Chiwetel Ejiofor"] },
  { r: 14, t: "The Avengers", g: 1515100211, y: 2012, o: 0, fa: 6.9, d: ["Joss Whedon"], a: ["Robert Downey Jr.", "Chris Evans", "Scarlett Johansson", "Mark Ruffalo", "Chris Hemsworth"] },
  { r: 15, t: "Furious 7", g: 1510065395, y: 2015, o: 0, d: ["James Wan"], a: ["Vin Diesel", "Paul Walker", "Dwayne Johnson", "Jason Statham", "Michelle Rodriguez"] },
  { r: 16, t: "Avatar: Fire and Ash", g: 1490386712, y: 2025, o: 0, fa: 6.3, d: ["James Cameron"], a: ["Sam Worthington", "Zoe Saldana", "Sigourney Weaver", "Kate Winslet", "Oona Chaplin"] },
  { r: 17, t: "Top Gun: Maverick", g: 1452163362, y: 2022, o: 1, d: ["Joseph Kosinski"], a: ["Tom Cruise", "Miles Teller", "Jennifer Connelly", "Jon Hamm", "Glen Powell"], oc: ["Mejor Sonido"] },
  { r: 18, t: "Frozen II", g: 1451653316, y: 2019, o: 0, d: ["Chris Buck", "Jennifer Lee"], a: ["Idina Menzel", "Kristen Bell", "Josh Gad", "Jonathan Groff", "Sterling K. Brown"] },
  { r: 19, t: "Barbie", g: 1447685476, y: 2023, o: 1, d: ["Greta Gerwig"], a: ["Margot Robbie", "Ryan Gosling", "Simu Liu", "Kate McKinnon", "America Ferrera"], oc: ["Mejor Canción Original"] },
  { r: 20, t: "Avengers: Age of Ultron", g: 1395316979, y: 2015, o: 0, fa: 6.3, d: ["Joss Whedon"], a: ["Robert Downey Jr.", "Chris Evans", "Chris Hemsworth", "Mark Ruffalo", "Scarlett Johansson"] },
  { r: 21, t: "The Super Mario Bros. Movie", g: 1359226275, y: 2023, o: 0, d: ["Aaron Horvath", "Michael Jelenic"], a: ["Chris Pratt", "Anya Taylor-Joy", "Charlie Day", "Jack Black", "Keegan-Michael Key"] },
  { r: 22, t: "The Odyssey", g: 1352782297, y: 2026, o: 0, d: ["Christopher Nolan"], a: ["Matt Damon", "Tom Holland", "Zendaya", "Anne Hathaway", "Charlize Theron"] },
  { r: 23, t: "Deadpool & Wolverine", g: 1338073645, y: 2024, o: 0, d: ["Shawn Levy"], a: ["Ryan Reynolds", "Hugh Jackman", "Emma Corrin", "Morena Baccarin", "Matthew Macfadyen"] },
  { r: 24, t: "Black Panther", g: 1334157082, y: 2018, o: 3, fa: 5.9, d: ["Ryan Coogler"], a: ["Chadwick Boseman", "Michael B. Jordan", "Lupita Nyong'o", "Danai Gurira", "Letitia Wright"], oc: ["Mejor Vestuario", "Mejor Diseño de Producción", "Mejor Banda Sonora"] },
  { r: 25, t: "Star Wars Ep. VIII: The Last Jedi", g: 1322581071, y: 2017, o: 0, d: ["Rian Johnson"], a: ["Mark Hamill", "Daisy Ridley", "Adam Driver", "Carrie Fisher", "John Boyega"] },
  { r: 26, t: "Harry Potter and the Deathly Hallows Part 2", g: 1312071376, y: 2011, o: 0, d: ["David Yates"], a: ["Daniel Radcliffe", "Emma Watson", "Rupert Grint", "Ralph Fiennes", "Alan Rickman"] },
  { r: 27, t: "Jurassic World: Fallen Kingdom", g: 1308323302, y: 2018, o: 0, fa: 5.5, d: ["J.A. Bayona"], a: ["Chris Pratt", "Bryce Dallas Howard", "Jeff Goldblum", "Rafe Spall", "James Cromwell"] },
  { r: 28, t: "Frozen", g: 1269253418, y: 2013, o: 2, d: ["Chris Buck", "Jennifer Lee"], a: ["Idina Menzel", "Kristen Bell", "Josh Gad", "Jonathan Groff", "Santino Fontana"], oc: ["Mejor Película de Animación", "Mejor Canción Original"] },
  { r: 29, t: "Beauty and the Beast (2017)", g: 1259761686, y: 2017, o: 0, d: ["Bill Condon"], a: ["Emma Watson", "Dan Stevens", "Luke Evans", "Kevin Kline", "Josh Gad"] },
  { r: 30, t: "Incredibles 2", g: 1242805359, y: 2018, o: 0, d: ["Brad Bird"], a: ["Craig T. Nelson", "Holly Hunter", "Samuel L. Jackson", "Sarah Vowell", "Huck Milner"] },
  { r: 31, t: "Iron Man 3", g: 1214630956, y: 2013, o: 0, fa: 6.1, d: ["Shane Black"], a: ["Robert Downey Jr.", "Gwyneth Paltrow", "Don Cheadle", "Guy Pearce", "Ben Kingsley"] },
  { r: 32, t: "The Fate of the Furious", g: 1189009332, y: 2017, o: 0, d: ["F. Gary Gray"], a: ["Vin Diesel", "Dwayne Johnson", "Jason Statham", "Charlize Theron", "Michelle Rodriguez"] },
  { r: 33, t: "Minions", g: 1157271759, y: 2015, o: 0, d: ["Pierre Coffin", "Kyle Balda"], a: ["Sandra Bullock", "Jon Hamm", "Michael Keaton", "Steve Carell", "Pierre Coffin"] },
  { r: 34, t: "Captain America: Civil War", g: 1151899586, y: 2016, o: 0, fa: 6.8, d: ["Anthony Russo", "Joe Russo"], a: ["Chris Evans", "Robert Downey Jr.", "Scarlett Johansson", "Sebastian Stan", "Chadwick Boseman"] },
  { r: 35, t: "Aquaman", g: 1148861807, y: 2018, o: 0, d: ["James Wan"], a: ["Jason Momoa", "Amber Heard", "Willem Dafoe", "Patrick Wilson", "Nicole Kidman"] },
  { r: 36, t: "Spider-Man: Far From Home", g: 1132298674, y: 2019, o: 0, fa: 6.1, d: ["Jon Watts"], a: ["Tom Holland", "Zendaya", "Jake Gyllenhaal", "Samuel L. Jackson", "Marisa Tomei"] },
  { r: 37, t: "Captain Marvel", g: 1129576094, y: 2019, o: 0, fa: 5.8, d: ["Anna Boden", "Ryan Fleck"], a: ["Brie Larson", "Samuel L. Jackson", "Ben Mendelsohn", "Jude Law", "Annette Bening"] },
  { r: 38, t: "The Lord of the Rings: The Return of the King", g: 1126146639, y: 2003, o: 11, fa: 8.2, d: ["Peter Jackson"], a: ["Elijah Wood", "Viggo Mortensen", "Ian McKellen", "Sean Astin", "Orlando Bloom"], oc: ["Mejor Película", "Mejor Director", "Mejor Guion Adaptado", "Mejor Montaje", "Mejor Dirección Artística", "Mejor Vestuario", "Mejor Maquillaje", "Mejor Banda Sonora", "Mejor Canción Original", "Mejor Mezcla de Sonido", "Mejores Efectos Visuales"] },
  { r: 39, t: "Transformers: Dark of the Moon", g: 1123794079, y: 2011, o: 0, d: ["Michael Bay"], a: ["Shia LaBeouf", "Rosie Huntington-Whiteley", "Josh Duhamel", "John Turturro", "Tyrese Gibson"] },
  { r: 40, t: "Toy Story 5", g: 1116377294, y: 2026, o: 0, d: ["Andrew Stanton"], a: ["Tom Hanks", "Tim Allen", "Annie Potts", "Keegan-Michael Key", "Joan Cusack"] },
  { r: 41, t: "Skyfall", g: 1110526981, y: 2012, o: 2, d: ["Sam Mendes"], a: ["Daniel Craig", "Javier Bardem", "Judi Dench", "Ralph Fiennes", "Naomie Harris"], oc: ["Mejor Edición de Sonido", "Mejor Canción Original"] },
  { r: 42, t: "Transformers: Age of Extinction", g: 1104054072, y: 2014, o: 0, d: ["Michael Bay"], a: ["Mark Wahlberg", "Stanley Tucci", "Kelsey Grammer", "Nicola Peltz", "Jack Reynor"] },
  { r: 43, t: "The Dark Knight Rises", g: 1082228107, y: 2012, o: 0, d: ["Christopher Nolan"], a: ["Christian Bale", "Tom Hardy", "Anne Hathaway", "Joseph Gordon-Levitt", "Gary Oldman"] },
  { r: 44, t: "Joker", g: 1078751311, y: 2019, o: 2, d: ["Todd Phillips"], a: ["Joaquin Phoenix", "Robert De Niro", "Zazie Beetz", "Frances Conroy", "Brett Cullen"], oc: ["Mejor Actor", "Mejor Banda Sonora"] },
  { r: 45, t: "Toy Story 4", g: 1071177215, y: 2019, o: 1, d: ["Josh Cooley"], a: ["Tom Hanks", "Tim Allen", "Annie Potts", "Tony Hale", "Keegan-Michael Key"], oc: ["Mejor Película de Animación"] },
  { r: 46, t: "Star Wars: The Rise of Skywalker", g: 1069951814, y: 2019, o: 0, d: ["J.J. Abrams"], a: ["Daisy Ridley", "Adam Driver", "John Boyega", "Oscar Isaac", "Mark Hamill"] },
  { r: 47, t: "Toy Story 3", g: 1068879522, y: 2010, o: 2, d: ["Lee Unkrich"], a: ["Tom Hanks", "Tim Allen", "Joan Cusack", "Ned Beatty", "Michael Keaton"], oc: ["Mejor Película de Animación", "Mejor Canción Original"] },
  { r: 48, t: "Pirates of the Caribbean: Dead Man's Chest", g: 1064479311, y: 2006, o: 1, d: ["Gore Verbinski"], a: ["Johnny Depp", "Orlando Bloom", "Keira Knightley", "Bill Nighy", "Stellan Skarsgård"], oc: ["Mejores Efectos Visuales"] },
  { r: 49, t: "Moana 2", g: 1059242164, y: 2024, o: 0, d: ["David Derrick Jr."], a: ["Auli'i Cravalho", "Dwayne Johnson", "Hualālai Chung", "Rose Matafeo", "David Fane"] },
  { r: 50, t: "Jurassic Park", g: 1058454230, y: 1993, o: 3, fa: 7.1, d: ["Steven Spielberg"], a: ["Sam Neill", "Laura Dern", "Jeff Goldblum", "Richard Attenborough", "Samuel L. Jackson"], oc: ["Mejores Efectos Visuales", "Mejor Sonido", "Mejor Edición de Sonido"] },
  { r: 51, t: "Rogue One: A Star Wars Story", g: 1055083596, y: 2016, o: 0, d: ["Gareth Edwards"], a: ["Felicity Jones", "Diego Luna", "Donnie Yen", "Mads Mikkelsen", "Ben Mendelsohn"] },
  { r: 52, t: "Star Wars Ep. I: The Phantom Menace", g: 1046513456, y: 1999, o: 0, d: ["George Lucas"], a: ["Liam Neeson", "Ewan McGregor", "Natalie Portman", "Jake Lloyd", "Ian McDiarmid"] },
  { r: 53, t: "Pirates of the Caribbean: On Stranger Tides", g: 1045713802, y: 2011, o: 0, d: ["Rob Marshall"], a: ["Johnny Depp", "Penélope Cruz", "Ian McShane", "Geoffrey Rush", "Kevin McNally"] },
  { r: 54, t: "Aladdin (2019)", g: 1042126107, y: 2019, o: 0, d: ["Guy Ritchie"], a: ["Will Smith", "Mena Massoud", "Naomi Scott", "Marwan Kenzari", "Navid Negahban"] },
  { r: 55, t: "Lilo & Stitch (2025)", g: 1038027526, y: 2025, o: 0, d: ["Dean Fleischer Camp"], a: ["Maia Kealoha", "Chris Sanders", "Sydney Agudong", "Zach Galifianakis", "Billy Magnussen"] },
  { r: 56, t: "Despicable Me 3", g: 1032809657, y: 2017, o: 0, d: ["Pierre Coffin", "Kyle Balda"], a: ["Steve Carell", "Kristen Wiig", "Trey Parker", "Steve Coogan", "Miranda Cosgrove"] },
  { r: 57, t: "Alice in Wonderland (2010)", g: 1025491110, y: 2010, o: 2, d: ["Tim Burton"], a: ["Mia Wasikowska", "Johnny Depp", "Helena Bonham Carter", "Anne Hathaway", "Crispin Glover"], oc: ["Mejor Dirección Artística", "Mejor Vestuario"] },
  { r: 58, t: "Finding Dory", g: 1025006125, y: 2016, o: 0, d: ["Andrew Stanton"], a: ["Ellen DeGeneres", "Albert Brooks", "Ed O'Neill", "Kaitlin Olson", "Ty Burrell"] },
  { r: 59, t: "Michael", g: 1021426595, y: 2026 },
  { r: 60, t: "Zootopia", g: 1018474875, y: 2016, o: 1, d: ["Byron Howard", "Rich Moore"], a: ["Ginnifer Goodwin", "Jason Bateman", "Idris Elba", "Jenny Slate", "Nate Torrence"], oc: ["Mejor Película de Animación"] },
  { r: 61, t: "The Hobbit: An Unexpected Journey", g: 1014938545, y: 2012, o: 0, d: ["Peter Jackson"], a: ["Martin Freeman", "Ian McKellen", "Richard Armitage", "Andy Serkis", "Hugo Weaving"] },
  { r: 62, t: "The Super Mario Galaxy Movie", g: 1012444492, y: 2026 },
  { r: 63, t: "The Dark Knight", g: 1010082145, y: 2008, o: 2, fa: 8.1, d: ["Christopher Nolan"], a: ["Christian Bale", "Heath Ledger", "Aaron Eckhart", "Michael Caine", "Gary Oldman"], oc: ["Mejor Actor de Reparto", "Mejor Edición de Sonido"] },
  { r: 64, t: "Jurassic World: Dominion", g: 1004004592, y: 2022, o: 0, fa: 4.8, d: ["Colin Trevorrow"], a: ["Chris Pratt", "Bryce Dallas Howard", "Sam Neill", "Laura Dern", "Jeff Goldblum"] },
  { r: 65, t: "The Lion King (1994)", g: 988389726, y: 1994, o: 2, fa: 7.9, d: ["Roger Allers", "Rob Minkoff"], a: ["Matthew Broderick", "James Earl Jones", "Jeremy Irons", "Nathan Lane", "Ernie Sabella"], oc: ["Mejor Banda Sonora", "Mejor Canción Original"] },
  { r: 66, t: "Despicable Me 4", g: 986706425, y: 2024, o: 0, d: ["Chris Renaud"], a: ["Steve Carell", "Kristen Wiig", "Will Ferrell", "Pierre Coffin", "Joey King"] },
  { r: 67, t: "Oppenheimer", g: 983148052, y: 2023, o: 7, d: ["Christopher Nolan"], a: ["Cillian Murphy", "Emily Blunt", "Robert Downey Jr.", "Matt Damon", "Florence Pugh"], oc: ["Mejor Película", "Mejor Director", "Mejor Actor", "Mejor Actor de Reparto", "Mejor Montaje", "Mejor Fotografía", "Mejor Banda Sonora"] },
  { r: 68, t: "Despicable Me 2", g: 975216835, y: 2013, o: 0, d: ["Pierre Coffin", "Chris Renaud"], a: ["Steve Carell", "Kristen Wiig", "Benjamin Bratt", "Miranda Cosgrove", "Russell Brand"] },
  { r: 69, t: "Harry Potter and the Sorcerer's Stone", g: 966637830, y: 2001, o: 0, d: ["Chris Columbus"], a: ["Daniel Radcliffe", "Emma Watson", "Rupert Grint", "Alan Rickman", "Maggie Smith"] },
  { r: 70, t: "Jumanji: Welcome to the Jungle", g: 961632807, y: 2017, o: 0, d: ["Jake Kasdan"], a: ["Dwayne Johnson", "Jack Black", "Kevin Hart", "Karen Gillan", "Nick Jonas"] },
  { r: 71, t: "A Minecraft Movie", g: 960387780, y: 2025, o: 0, d: ["Jared Hess"], a: ["Jason Momoa", "Jack Black", "Danielle Brooks", "Sebastian Hansen", "Jennifer Coolidge"] },
  { r: 72, t: "Pirates of the Caribbean: At World's End", g: 959681215, y: 2007, o: 0, d: ["Gore Verbinski"], a: ["Johnny Depp", "Orlando Bloom", "Keira Knightley", "Geoffrey Rush", "Bill Nighy"] },
  { r: 73, t: "The Hobbit: The Desolation of Smaug", g: 959358436, y: 2013, o: 0, d: ["Peter Jackson"], a: ["Martin Freeman", "Ian McKellen", "Richard Armitage", "Benedict Cumberbatch", "Orlando Bloom"] },
  { r: 74, t: "Doctor Strange in the Multiverse of Madness", g: 955775804, y: 2022, o: 0, fa: 6.4, d: ["Sam Raimi"], a: ["Benedict Cumberbatch", "Elizabeth Olsen", "Xochitl Gomez", "Rachel McAdams", "Chiwetel Ejiofor"] },
  { r: 75, t: "The Jungle Book (2016)", g: 950697998, y: 2016, o: 1, d: ["Jon Favreau"], a: ["Neel Sethi", "Bill Murray", "Ben Kingsley", "Idris Elba", "Scarlett Johansson"], oc: ["Mejores Efectos Visuales"] },
  { r: 76, t: "Harry Potter and the Deathly Hallows Part 1", g: 943476160, y: 2010, o: 0, d: ["David Yates"], a: ["Daniel Radcliffe", "Emma Watson", "Rupert Grint", "Ralph Fiennes", "Alan Rickman"] },
  { r: 77, t: "The Hobbit: The Battle of the Five Armies", g: 940323039, y: 2014, o: 0, d: ["Peter Jackson"], a: ["Martin Freeman", "Ian McKellen", "Richard Armitage", "Luke Evans", "Benedict Cumberbatch"] },
  { r: 78, t: "Minions: The Rise of Gru", g: 937706494, y: 2022, o: 0, d: ["Kyle Balda"], a: ["Steve Carell", "Pierre Coffin", "Taraji P. Henson", "Michelle Yeoh", "Jean-Claude Van Damme"] },
  { r: 79, t: "Harry Potter and the Order of the Phoenix", g: 937444235, y: 2007, o: 0, d: ["David Yates"], a: ["Daniel Radcliffe", "Emma Watson", "Rupert Grint", "Gary Oldman", "Ralph Fiennes"] },
  { r: 80, t: "Finding Nemo", g: 936094852, y: 2003, o: 1, d: ["Andrew Stanton"], a: ["Albert Brooks", "Ellen DeGeneres", "Alexander Gould", "Willem Dafoe", "Geoffrey Rush"], oc: ["Mejor Película de Animación"] },
  { r: 81, t: "Shrek 2", g: 933848612, y: 2004, o: 0, d: ["Andrew Adamson"], a: ["Mike Myers", "Eddie Murphy", "Cameron Diaz", "Antonio Banderas", "Julie Andrews"] },
  { r: 82, t: "The Lord of the Rings: The Two Towers", g: 926797210, y: 2002, o: 2, fa: 8.0, d: ["Peter Jackson"], a: ["Elijah Wood", "Viggo Mortensen", "Ian McKellen", "Orlando Bloom", "Sean Astin"], oc: ["Mejor Edición de Sonido", "Mejores Efectos Visuales"] },
  { r: 83, t: "Harry Potter and the Half-Blood Prince", g: 926055796, y: 2009, o: 0, d: ["David Yates"], a: ["Daniel Radcliffe", "Emma Watson", "Rupert Grint", "Michael Gambon", "Alan Rickman"] },
  { r: 84, t: "Star Wars Ep. III: Revenge of the Sith", g: 902891983, y: 2005, o: 0, d: ["George Lucas"], a: ["Ewan McGregor", "Natalie Portman", "Hayden Christensen", "Ian McDiarmid", "Samuel L. Jackson"] },
  { r: 85, t: "The Lord of the Rings: The Fellowship of the Ring", g: 901990952, y: 2001, o: 4, fa: 8.0, d: ["Peter Jackson"], a: ["Elijah Wood", "Ian McKellen", "Viggo Mortensen", "Sean Astin", "Orlando Bloom"], oc: ["Mejor Fotografía", "Mejor Maquillaje", "Mejor Banda Sonora", "Mejores Efectos Visuales"] },
  { r: 86, t: "Spider-Man 3", g: 896337268, y: 2007, o: 0, d: ["Sam Raimi"], a: ["Tobey Maguire", "Kirsten Dunst", "James Franco", "Thomas Haden Church", "Topher Grace"] },
  { r: 87, t: "Harry Potter and the Goblet of Fire", g: 886774160, y: 2005, o: 0, d: ["Mike Newell"], a: ["Daniel Radcliffe", "Emma Watson", "Rupert Grint", "Ralph Fiennes", "Robert Pattinson"] },
  { r: 88, t: "Ice Age: Dawn of the Dinosaurs", g: 886686817, y: 2009, o: 0, d: ["Carlos Saldanha"], a: ["Ray Romano", "John Leguizamo", "Denis Leary", "Queen Latifah", "Simon Pegg"] },
  { r: 89, t: "The Secret Life of Pets", g: 886013000, y: 2016, o: 0, d: ["Chris Renaud"], a: ["Louis C.K.", "Eric Stonestreet", "Kevin Hart", "Jenny Slate", "Ellie Kemper"] },
  { r: 90, t: "Ice Age: Continental Drift", g: 879765137, y: 2012, o: 0, d: ["Steve Martino"], a: ["Ray Romano", "John Leguizamo", "Denis Leary", "Queen Latifah", "Jennifer Lopez"] },
  { r: 91, t: "Bohemian Rhapsody", g: 879088897, y: 2018, o: 4, d: ["Bryan Singer"], a: ["Rami Malek", "Lucy Boynton", "Gwilym Lee", "Ben Hardy", "Joseph Mazzello"], oc: ["Mejor Actor", "Mejor Montaje", "Mejor Edición de Sonido", "Mejor Mezcla de Sonido"] },
  { r: 92, t: "Spectre", g: 879077344, y: 2015, o: 1, d: ["Sam Mendes"], a: ["Daniel Craig", "Christoph Waltz", "Léa Seydoux", "Ralph Fiennes", "Monica Bellucci"], oc: ["Mejor Canción Original"] },
  { r: 93, t: "Spider-Man: Homecoming", g: 878852749, y: 2017, o: 0, fa: 6.3, d: ["Jon Watts"], a: ["Tom Holland", "Michael Keaton", "Robert Downey Jr.", "Zendaya", "Marisa Tomei"] },
  { r: 94, t: "Harry Potter and the Chamber of Secrets", g: 876751253, y: 2002, o: 0, d: ["Chris Columbus"], a: ["Daniel Radcliffe", "Emma Watson", "Rupert Grint", "Kenneth Branagh", "Alan Rickman"] },
  { r: 95, t: "Batman v Superman: Dawn of Justice", g: 874360194, y: 2016, o: 0, d: ["Zack Snyder"], a: ["Ben Affleck", "Henry Cavill", "Amy Adams", "Jesse Eisenberg", "Gal Gadot"] },
  { r: 96, t: "Jurassic World Rebirth", g: 872446516, y: 2025, o: 0, d: ["Gareth Edwards"], a: ["Scarlett Johansson", "Jonathan Bailey", "Mahershala Ali", "Rupert Friend", "Manuel Garcia-Rulfo"] },
  { r: 97, t: "Guardians of the Galaxy Vol 2", g: 869087963, y: 2017, o: 0, fa: 6.7, d: ["James Gunn"], a: ["Chris Pratt", "Zoe Saldana", "Dave Bautista", "Kurt Russell", "Bradley Cooper"] },
  { r: 98, t: "The Hunger Games: Catching Fire", g: 864808014, y: 2013, o: 0, d: ["Francis Lawrence"], a: ["Jennifer Lawrence", "Josh Hutcherson", "Liam Hemsworth", "Philip Seymour Hoffman", "Woody Harrelson"] },
  { r: 99, t: "Black Panther: Wakanda Forever", g: 859208836, y: 2022, o: 1, fa: 5.6, d: ["Ryan Coogler"], a: ["Letitia Wright", "Lupita Nyong'o", "Danai Gurira", "Angela Bassett", "Tenoch Huerta"], oc: ["Mejor Vestuario"] },
  { r: 100, t: "Venom", g: 856081053, y: 2018, o: 0, d: ["Ruben Fleischer"], a: ["Tom Hardy", "Michelle Williams", "Riz Ahmed", "Woody Harrelson", "Jenny Slate"] },
];
